/*
 * Copyright 2023 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package models

import play.api.libs.json.{Json, OFormat}

final case class Country(code: String, name: String)

object Country {

  implicit lazy val format: OFormat[Country] = Json.format[Country]

  val countryByCode: Map[Int, Country] = Map(
    1 -> Country("GB", "United Kingdom"),
    2 -> Country("GI", "Gibraltar"),
    3 -> Country("GG", "Guernsey"),
    4 -> Country("JE", "Jersey"),
    5 -> Country("MT", "Malta"),
    6 -> Country("CQ", "Sark"),
    7 -> Country("IM", "Isle of Man"),
    8 -> Country("GB", "United Kingdom"),
    9 -> Country("FR", "France"),
    10 -> Country("GG", "Guernsey"),
    11 -> Country("AG", "Antigua and Barbuda"),
    12 -> Country("AU", "Australia"),
    13 -> Country("BS", "The Bahamas"),
    14 -> Country("BB", "Barbados"),
    15 -> Country("BM", "Bermuda"),
    16 -> Country("MV", "Maldives"),
    17 -> Country("KY", "Cayman Islands"),
    18 -> Country("CK", "Cook Islands"),
    19 -> Country("DM", "Dominica"),
    20 -> Country("FK", "Falkland Islands"),
    21 -> Country("FJ", "Fiji"),
    22 -> Country("KI", "Kiribati"),
    23 -> Country("JM", "Jamaica"),
    24 -> Country("HK", "Hong Kong"),
    25 -> Country("MU", "Mauritius"),
    26 -> Country("MS", "Montserrat"),
    27 -> Country("VU", "Vanuatu"),
    28 -> Country("NZ", "New Zealand"),
    29 -> Country("NF", "Norfolk Island"),
    30 -> Country("PG", "Papua New Guinea"),
    31 -> Country("SH", "Saint Helena"),
    32 -> Country("KN", "St Kitts and Nevis"),
    33 -> Country("VC", "St Vincent"),
    34 -> Country("SC", "Seychelles"),
    35 -> Country("SB", "Solomon Islands"),
    36 -> Country("TV", "Tuvalu"),
    37 -> Country("TT", "Trinidad and Tobago"),
    38 -> Country("TC", "Turks and Caicos Islands"),
    39 -> Country("VG", "Virgin Islands (British)"),
    40 -> Country("WS", "Samoa"),
    41 -> Country("AI", "Anguilla"),
    42 -> Country("GD", "Grenada"),
    43 -> Country("LC", "St Lucia"),
    44 -> Country("NR", "Nauru"),
    45 -> Country("GL", "Greenland"),
    46 -> Country("CA", "Canada"),
    47 -> Country("GU", "Guam"),
    48 -> Country("AC", "Ascension Island"),
    49 -> Country("BH", "Bahrain"),
    50 -> Country("BW", "Botswana"),
    51 -> Country("BN", "Brunei"),
    52 -> Country("MM", "Myanmar (Burma)"),
    53 -> Country("LK", "Sri Lanka"),
    54 -> Country("BT", "Bhutan"),
    55 -> Country("GM", "The Gambia"),
    56 -> Country("GH", "Ghana"),
    57 -> Country("GY", "Guyana"),
    58 -> Country("BQ", "British Antarctic Territories"),
    59 -> Country("IN", "India"),
    60 -> Country("JO", "Jordan"),
    61 -> Country("KE", "Kenya"),
    62 -> Country("KW", "Kuwait"),
    63 -> Country("LS", "Lesotho"),
    64 -> Country("LY", "Libya"),
    65 -> Country("MW", "Malawi"),
    66 -> Country("MY", "Malaysia"),
    67 -> Country("OM", "Oman"),
    68 -> Country("NG", "Nigeria"),
    69 -> Country("PK", "Pakistan"),
    70 -> Country("YE", "Yemen"),
    71 -> Country("QA", "Qatar"),
    72 -> Country("ZA", "South Africa"),
    73 -> Country("MY", "Malaysia"),
    74 -> Country("MY", "Malaysia"),
    75 -> Country("AE", "United Arab Emirates"),
    76 -> Country("SL", "Sierra Leone"),
    77 -> Country("SG", "Singapore"),
    78 -> Country("SZ", "Eswatini"),
    79 -> Country("TZ", "Tanzania"),
    80 -> Country("AE", "United Arab Emirates"),
    81 -> Country("UG", "Uganda"),
    82 -> Country("ZM", "Zambia"),
    83 -> Country("NA", "Namibia"),
    84 -> Country("BD", "Bangladesh"),
    85 -> Country("TO", "Tonga"),
    86 -> Country("GW", "Guinea-Bissau"),
    87 -> Country("MN", "Mongolia"),
    88 -> Country("KP", "North Korea"),
    89 -> Country("ST", "Sao Tome and Principe"),
    90 -> Country("CV", "Cape Verde"),
    91 -> Country("KM", "Comoros"),
    92 -> Country("GQ", "Equatorial Guinea"),
    93 -> Country("AS", "American Samoa"),
    94 -> Country("AG", "Antigua and Barbuda"),
    95 -> Country("VI", "Virgin Islands (American)"),
    96 -> Country("MF", "Saint Martin"),
    97 -> Country("RU", "Russia"),
    98 -> Country("AM", "Armenia"),
    99 -> Country("BY", "Belarus"),
    100 -> Country("KZ", "Kazakhstan"),
    101 -> Country("KG", "Kyrgyzstan"),
    102 -> Country("MD", "Moldova"),
    103 -> Country("TJ", "Tajikistan"),
    104 -> Country("TM", "Turkmenistan"),
    105 -> Country("UZ", "Uzbekistan"),
    106 -> Country("AZ", "Azerbaijan"),
    107 -> Country("EE", "Estonia"),
    108 -> Country("GE", "Georgia"),
    109 -> Country("LV", "Latvia"),
    110 -> Country("LT", "Lithuania"),
    111 -> Country("UA", "Ukraine"),
    // Note there is a gap between 111 and 114
    114 -> Country("GB", "United Kingdom"),
    115 -> Country("GB", "United Kingdom"),
    116 -> Country("GB", "United Kingdom"),
    117 -> Country("IE", "Ireland"),
    // Note there is a gap between 117 and 120
    120 -> Country("GB", "United Kingdom"),
    121 -> Country("AD", "Andorra"),
    122 -> Country("AT", "Austria"),
    123 -> Country("BE", "Belgium"),
    124 -> Country("BG", "Bulgaria"),
    125 -> Country("CS", "Czechoslovakia"),
    126 -> Country("DK", "Denmark"),
    127 -> Country("FI", "Finland"),
    128 -> Country("FR", "France"),
    129 -> Country("DE", "Germany"),
    130 -> Country("DE", "Germany"),
    131 -> Country("GR", "Greece"),
    132 -> Country("HU", "Hungary"),
    133 -> Country("IT", "Italy"),
    134 -> Country("LU", "Luxembourg"),
    135 -> Country("NL", "Netherlands"),
    136 -> Country("NO", "Norway"),
    137 -> Country("PL", "Poland"),
    138 -> Country("PT", "Portugal"),
    139 -> Country("RO", "Romania"),
    140 -> Country("ES", "Spain"),
    141 -> Country("SE", "Sweden"),
    142 -> Country("CH", "Switzerland"),
    143 -> Country("TR", "Turkey"),
    144 -> Country("RU", "Russia"),
    145 -> Country("YU", "Yugoslavia"),
    // Note there is a gap at 1146
    147 -> Country("MC", "Monaco"),
    148 -> Country("AL", "Albania"),
    149 -> Country("CY", "Cyprus"),
    150 -> Country("IS", "Iceland"),
    151 -> Country("LI", "Liechtenstein"),
    152 -> Country("FO", "Faroe Islands"),
    153 -> Country("SM", "San Marino"),
    154 -> Country("VA", "Vatican City"),
    155 -> Country("BA", "Bosnia and Herzegovina"),
    156 -> Country("HR", "Croatia"),
    157 -> Country("MK", "North Macedonia"),
    158 -> Country("SI", "Slovenia"),
    159 -> Country("YU", "Yugoslavia"),
    // Note there is a gap at 160
    161 -> Country("AF", "Afghanistan"),
    162 -> Country("DZ", "Algeria"),
    163 -> Country("AO", "Angola"),
    164 -> Country("AR", "Argentina"),
    165 -> Country("BO", "Bolivia"),
    166 -> Country("BR", "Brazil"),
    167 -> Country("KH", "Cambodia"),
    168 -> Country("CM", "Cameroon"),
    169 -> Country("CL", "Chile"),
    170 -> Country("CN", "China"),
    171 -> Country("CO", "Colombia"),
    172 -> Country("ZR", "Zaire"),
    173 -> Country("CR", "Costa Rica"),
    174 -> Country("CU", "Cuba"),
    175 -> Country("DO", "Dominican Republic"),
    176 -> Country("EC", "Ecuador"),
    177 -> Country("EG", "Egypt"),
    178 -> Country("SV", "El Salvador"),
    179 -> Country("ET", "Ethiopia"),
    180 -> Country("TW", "Taiwan"),
    181 -> Country("GT", "Guatemala"),
    182 -> Country("HT", "Haiti"),
    183 -> Country("BZ", "Belize"),
    184 -> Country("ID", "Indonesia"),
    185 -> Country("IR", "Iran"),
    186 -> Country("IQ", "Iraq"),
    187 -> Country("IL", "Israel"),
    188 -> Country("CI", "Ivory Coast"),
    189 -> Country("JP", "Japan"),
    190 -> Country("LB", "Lebanon"),
    191 -> Country("LR", "Liberia"),
    192 -> Country("MO", "Macau"),
    193 -> Country("MG", "Madagascar"),
    194 -> Country("MX", "Mexico"),
    195 -> Country("MA", "Morocco"),
    196 -> Country("MZ", "Mozambique"),
    197 -> Country("NP", "Nepal"),
    198 -> Country("AN", "Antilles"),
    199 -> Country("NC", "New Caledonia"),
    200 -> Country("NI", "Nicaragua"),
    201 -> Country("PA", "Panama"),
    202 -> Country("PY", "Paraguay"),
    203 -> Country("PE", "Peru"),
    204 -> Country("PH", "Philippines"),
    205 -> Country("PR", "Puerto Rico"),
    206 -> Country("ZW", "Zimbabwe"),
    207 -> Country("SA", "Saudi Arabia"),
    208 -> Country("SN", "Senegal"),
    209 -> Country("SO", "Somalia"),
    210 -> Country("KR", "South Korea"),
    211 -> Country("VN", "Vietnam"),
    212 -> Country("SD", "Sudan"),
    213 -> Country("SY", "Syria"),
    214 -> Country("TH", "Thailand"),
    215 -> Country("TG", "Togo"),
    216 -> Country("TN", "Tunisia"),
    217 -> Country("UY", "Uruguay"),
    218 -> Country("US", "United States"),
    219 -> Country("VE", "Venezuela"),
    220 -> Country("YE", "Yemen"),
    // Note there is a gap at 221
    222 -> Country("FR", "France"),
    223 -> Country("GA", "Gabon"),
    224 -> Country("LA", "Laos"),
    225 -> Country("RW", "Rwanda"),
    226 -> Country("CF", "Central African Republic"),
    227 -> Country("DJ", "Djibouti"),
    228 -> Country("SR", "Suriname"),
    229 -> Country("BI", "Burundi"),
    230 -> Country("HN", "Honduras"),
    231 -> Country("GN", "Guinea"),
    232 -> Country("BJ", "Benin"),
    233 -> Country("CG", "Congo"),
    234 -> Country("TD", "Chad"),
    // Note there is a gap between 234 and 239
    239 -> Country("ML", "Mali"),
    240 -> Country("MR", "Mauritania"),
    241 -> Country("NE", "Niger"),
    242 -> Country("CZ", "Czechia"),
    243 -> Country("SK", "Slovakia"),
    244 -> Country("PF", "French Polynesia"),
    245 -> Country("TA", "Tristan Da Cuhna"),
    246 -> Country("BF", "Burkina Faso"),
    // Note there is a gap at 247
    // 248 is Unknown
    // 249 is Not Yet Recorded
    // 250 is Stateless
    251 -> Country("AW", "Aruba"),
    252 -> Country("BV", "Bouvet Island"),
    253 -> Country("CC", "Cocos (Keeling) Islands"),
    254 -> Country("CX", "Christmas Island"),
    255 -> Country("EH", "Western Sahara"),
    256 -> Country("ER", "Eritrea"),
    257 -> Country("FM", "Micronesia"),
    258 -> Country("GF", "French Guiana"),
    259 -> Country("GP", "Guadeloupe"),
    260 -> Country("GS", "South Georgia and South Sandwich Island"),
    261 -> Country("HM", "Heard Island and McDonald Islands"),
    262 -> Country("IO", "British Indian Ocean Territories"),
    263 -> Country("MH", "Marshall Islands"),
    264 -> Country("MM", "Myanmar (Burma)"),
    265 -> Country("NP", "Northern Mariana Islands"),
    266 -> Country("MQ", "Martinique"),
    267 -> Country("NU", "Niue"),
    268 -> Country("FP", "French Polynesia"),
    269 -> Country("PM", "Saint Pierre and Miquellon"),
    270 -> Country("PN", "Pitcairn"),
    271 -> Country("PW", "Palau"),
    272 -> Country("RE", "Réunion"),
    273 -> Country("SJ", "Svalbard and Jan Mayen"),
    274 -> Country("TF", "French Southern Territories"),
    275 -> Country("TK", "Tokelau"),
    276 -> Country("TL", "East Timor"),
    277 -> Country("UM", "United States Minor Outlying Islands"),
    278 -> Country("WF", "Wallis and Futuna"),
    279 -> Country("YT", "Mayotte"),
    280 -> Country("CD", "Congo (Democratic Republic)"),
    281 -> Country("KH", "Cambodia"),
    282 -> Country("RU", "Russia"),
    283 -> Country("ME", "Montenegro"),
    284 -> Country("RS", "Serbia"),
    285 -> Country("AQ", "Antarctica"),
    286 -> Country("XK", "Kosovo")
  )
}